import {
  Atom,
  BookOpen,
  Calculator,
  Code2,
  FlaskConical,
  Languages,
  Lightbulb,
  Music2,
  Palette,
  Globe2,
  Mic2,
  BriefcaseBusiness,
} from 'lucide-react';

export const subjects = [
  { name: 'Toán học', icon: Calculator, color: 'green' },
  { name: 'Tiếng Anh', icon: Languages, color: 'violet' },
  { name: 'Vật lý', icon: Atom, color: 'blue' },
  { name: 'Hóa học', icon: FlaskConical, color: 'cyan' },
  { name: 'Ngữ văn', icon: BookOpen, color: 'rose' },
  { name: 'Lập trình', icon: Code2, color: 'blue' },
  { name: 'Piano', icon: Music2, color: 'neutral' },
  { name: 'Mỹ thuật', icon: Palette, color: 'orange' },
  { name: 'Kỹ năng sống', icon: Lightbulb, color: 'amber' },
  { name: 'Tiếng Nhật', icon: Globe2, color: 'rose' },
  { name: 'Thanh nhạc', icon: Mic2, color: 'violet' },
  { name: 'Kinh doanh', icon: BriefcaseBusiness, color: 'green' },
];

// Sample content based on the supplied design reference; replace with API data when available.
export const tutors = [
  {
    id: 'mai-anh',
    title: 'Cô',
    name: 'Trần Thị Mai Anh',
    subject: 'Tiếng Anh',
    rating: 5.0,
    reviews: 120,
    heartCount: 486,
    experience: 6,
    price: 350000,
    mode: 'online',
    image: '/images/teacher-mai-anh.jpg',
    description:
      'Chuyên luyện thi IELTS và tiếng Anh giao tiếp. Lộ trình cá nhân hoá cho từng học viên.',
    bio: 'Tạo không gian học thoải mái, giúp học viên tự tin sử dụng tiếng Anh mỗi ngày.',
    methods: [
      'Đánh giá trình độ và mục tiêu đầu vào',
      'Luyện tập thực tế qua từng buổi học',
      'Theo dõi tiến bộ và phản hồi cá nhân',
    ],
  },
  {
    id: 'van-hai',
    title: 'ThS.',
    name: 'Nguyễn Văn Hải',
    subject: 'Toán học',
    rating: 4.9,
    reviews: 98,
    heartCount: 412,
    experience: 8,
    price: 250000,
    mode: 'both',
    image: '/images/teacher-van-hai.jpg',
    description:
      'Vững kiến thức nền tảng, tự tin chinh phục kỳ thi. Giải thích dễ hiểu, học từ bản chất.',
    bio: 'Đồng hành cùng học sinh THCS, THPT, luyện thi tốt nghiệp và đại học.',
    methods: [
      'Củng cố nền tảng theo năng lực',
      'Hướng dẫn tư duy giải quyết vấn đề',
      'Ôn tập theo mục tiêu của học viên',
    ],
  },
  {
    id: 'minh-tuan',
    title: 'Thầy',
    name: 'Lê Minh Tuấn',
    subject: 'Lập trình',
    rating: 4.8,
    reviews: 86,
    heartCount: 365,
    experience: 4,
    price: 300000,
    mode: 'online',
    image: '/images/teacher-minh-tuan.jpg',
    description: 'Từ dòng code đầu tiên đến dự án thực tế. Học lập trình dễ hiểu, thực hành ngay.',
    bio: 'Hướng dẫn Python, JavaScript và lập trình web cho người mới bắt đầu.',
    methods: [
      'Học qua những bài tập nhỏ',
      'Xây dựng dự án cá nhân',
      'Nhận phản hồi trực tiếp về mã nguồn',
    ],
  },
  {
    id: 'thu-trang',
    title: 'ThS.',
    name: 'Phạm Thu Trang',
    subject: 'Piano',
    rating: 4.7,
    reviews: 64,
    heartCount: 298,
    experience: 7,
    price: 400000,
    mode: 'both',
    image: '/images/teacher-thu-trang.jpg',
    description:
      'Khơi dậy tình yêu âm nhạc. Học piano từ cơ bản đến nâng cao, phù hợp mọi lứa tuổi.',
    bio: 'Kết hợp kỹ thuật và cảm thụ âm nhạc để mỗi buổi học đều thú vị.',
    methods: [
      'Làm quen nhạc lý và bàn phím',
      'Luyện tập với bài nhạc yêu thích',
      'Phát triển kỹ thuật biểu diễn',
    ],
  },
  {
    id: 'thanh-lam',
    title: 'Cô',
    name: 'Nguyễn Thanh Lam',
    subject: 'Ngữ văn',
    rating: 4.9,
    reviews: 52,
    heartCount: 266,
    experience: 5,
    price: 220000,
    mode: 'both',
    image: '/images/teacher-thu-trang.jpg',
    description: 'Đọc sâu, viết rõ và cảm nhận văn học. Bồi dưỡng tư duy, luyện kỹ năng viết bài.',
    bio: 'Giúp học viên diễn đạt ý tưởng bằng ngôn ngữ của chính mình.',
    methods: [
      'Đọc hiểu theo chủ đề',
      'Luyện lập luận và cấu trúc bài',
      'Chỉnh sửa bài viết cá nhân',
    ],
  },
  {
    id: 'quang-huy',
    title: 'Thầy',
    name: 'Trần Quang Huy',
    subject: 'Vật lý',
    rating: 4.8,
    reviews: 47,
    heartCount: 244,
    experience: 6,
    price: 280000,
    mode: 'online',
    image: '/images/teacher-van-hai.jpg',
    description: 'Hiểu các hiện tượng từ cuộc sống. Củng cố kiến thức và rèn kỹ năng giải bài tập.',
    bio: 'Biến những khái niệm trừu tượng thành ví dụ dễ hiểu.',
    methods: [
      'Giải thích bằng ví dụ thực tế',
      'Hệ thống công thức theo chủ đề',
      'Luyện tập theo trình độ',
    ],
  },
  {
    id: 'bao-ngoc',
    title: 'Cô',
    name: 'Lê Bảo Ngọc',
    subject: 'Hóa học',
    rating: 4.9,
    reviews: 71,
    heartCount: 320,
    experience: 5,
    price: 250000,
    mode: 'both',
    image: '/images/teacher-mai-anh.jpg',
    description: 'Nắm chắc lý thuyết, hiểu rõ phản ứng. Lộ trình học tập phù hợp từng mục tiêu.',
    bio: 'Hướng dẫn học sinh THCS và THPT tiếp cận môn Hóa một cách khoa học.',
    methods: [
      'Xây dựng sơ đồ kiến thức',
      'Luyện giải bài theo phương pháp',
      'Ôn tập có phản hồi cá nhân',
    ],
  },
  {
    id: 'duc-minh',
    title: 'Thầy',
    name: 'Đỗ Đức Minh , Chuẩn Tiến sĩ',
    subject: 'Mỹ thuật',
    rating: 4.7,
    reviews: 35,
    heartCount: 197,
    experience: 4,
    price: 300000,
    mode: 'both',
    image: '/images/teacher-minh-tuan.jpg',
    description:
      'Khám phá màu sắc và nuôi dưỡng sáng tạo. Học vẽ theo sở thích, phát triển phong cách riêng.',
    bio: 'Hướng dẫn từ phác thảo cơ bản đến hoàn thiện tác phẩm.',
    methods: [
      'Rèn quan sát và dựng hình',
      'Khám phá chất liệu và màu sắc',
      'Phát triển ý tưởng cá nhân',
    ],
  },
];

export const testimonials = [
  {
    name: 'Nguyễn Minh Quân',
    role: 'Học sinh lớp 12',
    image: '/images/student-quan.jpg',
    quote:
      'Nhờ EduMatch, mình tìm được gia sư Toán rất phù hợp. Thầy dạy dễ hiểu, giúp mình tự tin hơn mỗi ngày.',
  },
  {
    name: 'Trần Khánh Linh',
    role: 'Sinh viên',
    image: '/images/student-linh.jpg',
    quote:
      'Cô giáo rất kiên nhẫn và luôn khuyến khích mình nói tiếng Anh. Mỗi buổi học đều có thêm một điều mới.',
  },
  {
    name: 'Lê Hoàng Nam',
    role: 'Phụ huynh học sinh',
    image: '/images/student-nam.jpg',
    quote:
      'Hồ sơ rõ ràng, dễ tìm giáo viên phù hợp với con. Lịch học linh hoạt giúp gia đình sắp xếp thuận tiện hơn.',
  },
];
